/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.55
 * Generated at: 2022-02-18 16:16:45 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.Pagine;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Register_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>Insert title here</title>\n");
 String errore = (String) request.getAttribute("errore");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<link\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css\"\n");
      out.write("	rel=\"stylesheet\"\n");
      out.write("	integrity=\"sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3\"\n");
      out.write("	crossorigin=\"anonymous\">\n");
      out.write("	<link rel=\"stylesheet\" type=\"text/css\" href=\"Style.css\">\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("	<div class=\"container\">\n");
      out.write("		<div class=\"row justify-content-center\">\n");
      out.write("			<div class=\"col-12 col-md-6 text-center\">\n");
      out.write("				<h2>Accedi</h2>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("		<div class=\"row justify-content-center\">\n");
      out.write("			<div class=\"col-12 col-md-6\">\n");
      out.write("				<form action=\"s2?z=2\" method=\"Post\">\n");
      out.write("					<div class=\"mb-3\">\n");
      out.write("						<label for=\"name\" class=\"form-label\">Nome </label> <input\n");
      out.write("							type=\"text\" name=\"nome\" class=\"form-control\" id=\"nome\"\n");
      out.write("							aria-describedby=\"emailHelp\">\n");
      out.write("						<div id=\"emailHelp\" class=\"form-text\"></div>\n");
      out.write("					</div>\n");
      out.write("					<div class=\"mb-3\">\n");
      out.write("						<label for=\"cognome\" class=\"form-label\">Cognome\n");
      out.write("						</label> <input type=\"text\"name=\"cognome\" class=\"form-control\" id=\"cognome\"\n");
      out.write("							aria-describedby=\"emailHelp\">\n");
      out.write("						\n");
      out.write("					</div>\n");
      out.write("					<div class=\"mb-3\">\n");
      out.write("						<label for=\"exampleInputEmail1\" class=\"form-label\">Inserisci\n");
      out.write("							Email </label> \n");
      out.write("							<input type=\"email\" class=\"form-control\" name=\"email\"\n");
      out.write("							id=\"exampleInputEmail1\" aria-describedby=\"emailHelp\">\n");
      out.write("						<div id=\"emailHelp\" class=\"form-text\"></div>\n");
      out.write("					</div>\n");
      out.write("					<div class=\"mb-3\">\n");
      out.write("						<label for=\"exampleInputEmail1\" class=\"form-label\">Reinserisci\n");
      out.write("							Email </label> <input type=\"email\" class=\"form-control\" name=\"email\" \n");
      out.write("							id=\"exampleInputEmail1\" aria-describedby=\"emailHelp\">\n");
      out.write("						<div id=\"emailHelp\" class=\"form-text\"></div>\n");
      out.write("					</div>\n");
      out.write("					<div class=\"mb-3\">\n");
      out.write("						<label for=\"exampleInputPassword1\" class=\"form-label\">Password</label>\n");
      out.write("						<input type=\"password\" class=\"form-control\" name=\"password\"\n");
      out.write("							id=\"exampleInputPassword1\">\n");
      out.write("					</div>\n");
      out.write("\n");
      out.write("					<button type=\"submit\" class=\"btn btn-primary\">Submit</button>\n");
      out.write("				</form>\n");
      out.write("			</div>\n");
      out.write("			");
if(errore != null){
				
      out.write("\n");
      out.write("				<h3 class=\"text-center color\">");
      out.print( errore );
      out.write("</h3>\n");
      out.write("		");
	} 
      out.write("\n");
      out.write("				<a href=\"s2?z=1\" class=\"text-center mt-5\"><button class=\" btn btn-primary\">Accedi\n");
      out.write("						</button></a>\n");
      out.write("			<a href=\"s1?z=4\" class=\"text-center mt-5\"><button class=\" btn btn-primary\">Torna\n");
      out.write("						alla home</button></a>\n");
      out.write("		</div>\n");
      out.write("\n");
      out.write("	</div>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
